name: deploy on production

on: 
    push:
        branches:
            - main  

jobs:
    deploy:
        name: Push to AWS Server
        runs-on: ubuntu-latest

        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: Execute remote SSH commands using SSH key
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: echo "Hello SSH is logged in Successfully"

        